#+TITLE: ISO 20022 to ledger-cli

Convert [[https://en.wikipedia.org/wiki/ISO_20022][ISO 20022]] to the [[https://www.ledger-cli.org][ledger-cli]] plain text accounting format.

Obviously this goes without saying: This software is provided "as is"
without warranty of any kind. If your ledger statements are incorrect
and you believe you found a bug in the converter please file an issue
or even better a pull request.

* Usage

#+BEGIN_SRC shell
clj -m iso-to-ledger iso_20022.xml > plain_text.ledger
#+END_SRC

* Requirements

You will need ~clj~ to run this code. Install as described in
[[https://clojure.org/guides/getting_started][Getting Started]].

* Todo

- [ ] Add some machine learning to classify the transactions,
  i.e. assign the right account and payee to a transaction.

* Feedback

If you have any suggestions or problems let me know. Issues and Pull
Requests are very welcome.

* References

The conversion is mostly based on classic reverse engineering of
sample xml data. When in doubt also some [[https://www.six-group.com/interbank-clearing/dam/downloads/de/standardization/iso/swiss-recommendations/implementation-guidelines-camt.pdf][official implementation
guidelines]] were consulted.

* License

GPLv3+
